# S.O.N.I.A. Continuous Integration Configuration File
# Author: Thibaut Mattio

# General setup
# -------------
language:
  - cpp
  - python

python:
  - "2.7"

compiler:
  - gcc

os:
  - linux

dist: trusty

branches:
  only:
    - master
    - develop

notifications:
  slack:
    rooms:
      - sonia-auv:VuDl4QAG49oxkr53yCiKMAxH
    on_success: always
    on_failure: always

# Allow caching of debian (apt-get) packages. This means they're cached
# on Travis, so we still have to download/install them, but it will be
# faster than going to the ubuntu repositories.
cache: apt
# Before anything, see if we can get the mongoDB troubles out of the way.
# Note that this is a Travis-CI specific problem; this is not needed in
# general.
before_install: # Use this to prepare the system to install prerequisites or dependencies
  # Define some config vars
  - export ROS_DISTRO=indigo
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_ORG=sonia-auv
  - export REPOSITORY_NAME=provider_sonar
  - export ROS_CI_DESKTOP=`lsb_release -cs`
  - export PYTHONPATH='$PYTHONPATH:/opt/ros/indigo/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages/'

# Commands to install dependencies
# --------------------------------
install:
  # Install ROS
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-catkin-pkg python-rosdep python-wstool ros-$ROS_DISTRO-catkin ros-$ROS_DISTRO-ros libeigen3-dev
  - source /opt/ros/$ROS_DISTRO/setup.bash
  # Setup rosdep
  - sudo rosdep init
  - rosdep update
  # Sourcing ROS exec
  - source /opt/ros/$ROS_DISTRO/setup.bash
  # Create workspace.
  - mkdir -p ~/catkin_ws/src
  - mv $CI_SOURCE_PATH ~/catkin_ws/src/$REPOSITORY_NAME
  - cd ~/catkin_ws/src
  - catkin_init_workspace
  # Cloning dependencies
  - git clone https://github.com/sonia-auv/lib_atlas.git -b develop
  - git clone https://github.com/sonia-auv/sonia_msgs.git -b develop
  # Install dependencies
  - cd ~/catkin_ws/
  - rosdep install --from-paths src --ignore-src --rosdistro=${ROS_DISTRO} -y
  # Build
  - catkin_make

# Command to run tests
# --------------------
script:
  - catkin_make run_tests
