#**************************************
#**********Sonar parameters************
#**************************************
#Frame id of the sonar
/provider_sonar/sonar/frame_id_ : "BODY"
#Serial port the sonar is connected to 
/provider_sonar/sonar/port_ : "/dev/ttyS3"
#Number of measurements to be taken 
/provider_sonar/sonar/n_bins_ : 400
#Sonar range (m)
/provider_sonar/sonar/range_ : 8.0
#Velocity of sound in water 
/provider_sonar/sonar/vos_ : 1500.0
#Angle between two consecutive steps, in 1/16 gradians:
#32 = 1.8ยบ, 16 = 0.9ยบ, 8 = 0.45ยบ, 4 = 0.225ยบ
/provider_sonar/sonar/angle_step_size_ : 16
#Left Limit of scanning sector
/provider_sonar/sonar/left_limit_ : 2400
#Right limit of scanning sector
/provider_sonar/sonar/right_limit_ : 4000
#Debug mode for the driver 
/provider_sonar/sonar/use_debug_mode_ : false

#**************************************
#********Simulation parameters*********
#**************************************
#Simulate the sonar
/provider_sonar/simulate/simulate_ : false
/provider_sonar/simulate/simulate_n_bins_ : 400
/provider_sonar/simulate/simulate_bin_distance_step_ : 1.0
/provider_sonar/simulate/simulate_distance_ : 8.0
/provider_sonar/simulate/simulate_intensity_ : 255
/provider_sonar/simulate/simulate_intensity_variance_ : 10.0
/provider_sonar/simulate/simulate_use_manual_angle_ : false
/provider_sonar/simulate/simulate_manual_angle_ : 180.0
/provider_sonar/simulate/simulate_scan_angle_velocity_ : 180.0

#**************************************
#********Point Cloud parameters********
#**************************************
/provider_sonar/point_cloud/use_point_cloud_threshold_ : true
/provider_sonar/point_cloud/min_distance_threshold_ : 0
/provider_sonar/point_cloud/min_point_cloud_intensity_threshold_ : 0
/provider_sonar/point_cloud/only_first_point_ : false
